// Using jsPDF library
function downloadPDFReport() {
  // Get data from analytics
  const data = {
    name: JSON.parse(localStorage.getItem('user')).name,
    totalAttempts: document.getElementById('totalAttempts').textContent,
    averageScore: document.getElementById('averageScore').textContent,
    bestScore: document.getElementById('bestScore').textContent,
    worstScore: document.getElementById('worstScore').textContent
  };

  // Create PDF content
  const content = `
AI Interview Performance Report
================================

Candidate: ${data.name}
Date: ${new Date().toLocaleDateString()}

Performance Summary:
- Total Attempts: ${data.totalAttempts}
- Average Score: ${data.averageScore}/10
- Best Score: ${data.bestScore}/10
- Worst Score: ${data.worstScore}/10

Strengths:
${Array.from(document.getElementById('strengths').children)
  .map(li => '- ' + li.textContent)
  .join('\n')}

Areas for Improvement:
${Array.from(document.getElementById('weaknesses').children)
  .map(li => '- ' + li.textContent)
  .join('\n')}

Generated by AI Interview Platform
  `;

  // Download as text file (simple approach)
  const blob = new Blob([content], { type: 'text/plain' });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `interview-report-${Date.now()}.txt`;
  a.click();
}

function downloadCSVReport() {
  const csv = `Metric,Value
Total Attempts,${document.getElementById('totalAttempts').textContent}
Average Score,${document.getElementById('averageScore').textContent}
Best Score,${document.getElementById('bestScore').textContent}
Worst Score,${document.getElementById('worstScore').textContent}
`;

  const blob = new Blob([csv], { type: 'text/csv' });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `interview-report-${Date.now()}.csv`;
  a.click();
}